import React, { useMemo, useState } from 'react';
import { findLocalUser, getCurrentLocalUserEmail } from './localAuthStore';
import Select from './components/Select';

const TeacherSettings = () => {
  const currentEmail = getCurrentLocalUserEmail();
  const storedTeacher = currentEmail ? findLocalUser(currentEmail) : null;

  const [notificationPrefs, setNotificationPrefs] = useState({
    submissions: true,
    returnedResults: true,
    gradingReminders: false,
  });
  const [defaultView, setDefaultView] = useState('subjects');
  const [timeZone, setTimeZone] = useState('Asia/Manila');
  const [workflowPrefs, setWorkflowPrefs] = useState({
    autoGenerateDrafts: true,
    exactScoreDisplay: true,
    openFirstSubmissionFile: true,
    autoArchiveCompleted: false,
  });

  const fullName = `${storedTeacher?.firstName ?? 'Teacher'} ${storedTeacher?.lastName ?? ''}`.trim();

  const toggles = useMemo(
    () => [
      {
        label: 'New submission alerts',
        key: 'submissions',
        description: 'Notify you when students submit new work for grading.',
      },
      {
        label: 'Returned result updates',
        key: 'returnedResults',
        description: 'Keep reminders visible when feedback has been sent back to students.',
      },
      {
        label: 'Grading reminders',
        key: 'gradingReminders',
        description: 'Show reminders for pending ungraded submissions in your workflow.',
      },
    ],
    []
  );

  const workflowToggles = useMemo(
    () => [
      {
        label: 'Auto-generate draft on review',
        key: 'autoGenerateDrafts',
        description: 'Prepare an AI draft score and feedback when you start reviewing a submission.',
      },
      {
        label: 'Show exact score with percentage',
        key: 'exactScoreDisplay',
        description: 'Display both the percentage and the exact earned score in reports and feedback.',
      },
      {
        label: 'Open first submission file automatically',
        key: 'openFirstSubmissionFile',
        description: 'Start each review with the first uploaded solution file already selected.',
      },
      {
        label: 'Auto-archive completed assessments',
        key: 'autoArchiveCompleted',
        description: 'Move finished assessments out of the active workflow once all results are returned.',
      },
    ],
    []
  );

  const handleToggle = (key) => {
    setNotificationPrefs((prev) => ({ ...prev, [key]: !prev[key] }));
  };

  const handleWorkflowToggle = (key) => {
    setWorkflowPrefs((prev) => ({ ...prev, [key]: !prev[key] }));
  };

  return (
    <div className="h-full min-h-0 overflow-y-auto teacher-scrollbar px-1 pt-3 sm:px-2">
      <div className="mx-auto flex max-w-[1100px] flex-col gap-2">
      <section className="shrink-0 rounded-xl bg-gradient-to-r from-blue-500 via-blue-600 to-indigo-600 px-4 py-3 mb-0">
        <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
          <div className="space-y-0.5">
            <div className="flex items-center gap-2.5">
              <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-white/20 text-white">
                <svg viewBox="0 0 20 20" fill="currentColor" className="h-4 w-4">
                  <path fillRule="evenodd" d="M7.84 1.804A1 1 0 018.82 1h2.36a1 1 0 01.98.804l.331 1.652a6.993 6.993 0 011.929 1.115l1.598-.54a1 1 0 011.186.447l1.18 2.044a1 1 0 01-.205 1.251l-1.267 1.113a7.047 7.047 0 010 2.228l1.267 1.113a1 1 0 01.206 1.25l-1.18 2.045a1 1 0 01-1.187.447l-1.598-.54a6.993 6.993 0 01-1.929 1.115l-.33 1.652a1 1 0 01-.98.804H8.82a1 1 0 01-.98-.804l-.331-1.652a6.993 6.993 0 01-1.929-1.115l-1.598.54a1 1 0 01-1.186-.447l-1.18-2.044a1 1 0 01.205-1.251l1.267-1.114a7.05 7.05 0 010-2.227L1.821 7.773a1 1 0 01-.206-1.25l1.18-2.045a1 1 0 011.187-.447l1.598.54A6.992 6.992 0 017.51 3.456l.33-1.652zM10 13a3 3 0 100-6 3 3 0 000 6z" clipRule="evenodd" />
                </svg>
              </div>
              <h2 className="text-lg font-bold text-white">Classroom Controls</h2>
            </div>
            <p className="text-xs text-blue-100 ml-[42px]">Customize AlgebraAssess so your workflow matches your grading rhythm.</p>
          </div>
        </div>
        <div className="mt-3 grid gap-2 md:grid-cols-2">
          <div className="rounded-lg border border-white/20 bg-white/10 p-3">
            <p className="text-[10px] uppercase tracking-wider text-blue-200">Logged in as</p>
            <p className="mt-0.5 text-sm font-semibold text-white">{fullName}</p>
            <p className="text-xs text-blue-200">{storedTeacher?.email ?? 'teacher@example.com'}</p>
          </div>
          <div className="rounded-lg border border-white/20 bg-white/10 p-3">
            <p className="text-[10px] uppercase tracking-wider text-blue-200">Default view</p>
            <div className="mt-1.5 flex gap-1.5 flex-wrap">
              {['subjects', 'submissions', 'reports'].map((entry) => (
                <button
                  key={entry}
                  type="button"
                  onClick={() => setDefaultView(entry)}
                  className={`rounded-full px-3 py-1 text-xs font-semibold transition ${entry === defaultView ? 'bg-white text-blue-600' : 'border border-white/30 text-white hover:bg-white/10'}`}
                >
                  {entry.charAt(0).toUpperCase() + entry.slice(1)}
                </button>
              ))}
            </div>
            <p className="text-[10px] text-blue-200 mt-1">Choose the page you want to land on after login.</p>
          </div>
        </div>
      </section>

      <section className="grid gap-4 lg:grid-cols-2">
        <article className="teacher-float-card space-y-3 p-4">
          <div>
            <p className="text-[10px] uppercase tracking-[0.3em] text-slate-400">Notifications</p>
            <h2 className="text-base font-bold text-slate-900">Teacher alerts</h2>
          </div>
          <div className="space-y-2">
            {toggles.map((toggle) => (
              <div
                key={toggle.key}
                className="teacher-float-card flex items-center justify-between px-3 py-2.5"
              >
                <div>
                  <p className="text-sm font-semibold text-slate-900">{toggle.label}</p>
                  <p className="text-xs text-slate-500">{toggle.description}</p>
                </div>
                <label className="relative inline-flex cursor-pointer items-center">
                  <input
                    type="checkbox"
                    checked={notificationPrefs[toggle.key]}
                    onChange={() => handleToggle(toggle.key)}
                    className="peer sr-only"
                  />
                  <span className="h-5 w-10 rounded-full bg-slate-200 transition peer-checked:bg-blue-600"></span>
                  <span className="absolute left-0.5 top-0.5 h-4 w-4 rounded-full bg-white shadow transition peer-checked:left-5"></span>
                </label>
              </div>
            ))}
          </div>
        </article>
        <article className="teacher-float-card space-y-3 p-4">
          <div>
            <p className="text-[10px] uppercase tracking-[0.3em] text-slate-400">Workflow controls</p>
            <h2 className="text-base font-bold text-slate-900">Review preferences</h2>
          </div>
          <div className="space-y-2">
            <label className="block text-[10px] font-semibold uppercase tracking-[0.3em] text-slate-400">Time zone</label>
            <Select
              value={timeZone}
              onChange={(e) => setTimeZone(e.target.value)}
            >
              <option>Asia/Manila</option>
              <option>Asia/Singapore</option>
              <option>America/New_York</option>
              <option>UTC</option>
            </Select>
            {workflowToggles.map((toggle) => (
              <div
                key={toggle.key}
                className="teacher-float-card flex items-center justify-between px-3 py-2.5"
              >
                <div>
                  <p className="text-sm font-semibold text-slate-900">{toggle.label}</p>
                  <p className="text-xs text-slate-500">{toggle.description}</p>
                </div>
                <label className="relative inline-flex cursor-pointer items-center">
                  <input
                    type="checkbox"
                    checked={workflowPrefs[toggle.key]}
                    onChange={() => handleWorkflowToggle(toggle.key)}
                    className="peer sr-only"
                  />
                  <span className="h-5 w-10 rounded-full bg-slate-200 transition peer-checked:bg-blue-600"></span>
                  <span className="absolute left-0.5 top-0.5 h-4 w-4 rounded-full bg-white shadow transition peer-checked:left-5"></span>
                </label>
              </div>
            ))}
            <p className="text-[10px] text-slate-500">Settings are saved locally and synced with your account.</p>
          </div>
        </article>
      </section>
      </div>
    </div>
  );
};

export default TeacherSettings;
